(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))a(n);new MutationObserver(n=>{for(const s of n)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(n){const s={};return n.integrity&&(s.integrity=n.integrity),n.referrerPolicy&&(s.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?s.credentials="include":n.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(n){if(n.ep)return;n.ep=!0;const s=r(n);fetch(n.href,s)}})();function k(e){const t={update(n){this.lastData!==n&&(r(n),this.lastData=n)},callback:n=>{}};return t;function r(n){e.innerText="",n.map(s=>{const l=document.createElement("details");l.classList.add("details");const o=document.createElement("summary");o.appendChild(a(s,"level0")),l.appendChild(o);for(let u of s.children)l.appendChild(a(u,"level1",C));return l}).forEach(s=>{e.appendChild(s)})}function a(n,s,l){const o=document.createElement("a");return o.href="#",o.classList.add(s),o.appendChild(document.createTextNode(((l==null?void 0:l(n.key))??n.key)+" ("+n.count+")")),o.addEventListener("click",()=>(t.callback(n.firstId),!1)),o}}function C(e){return months[e-1]}function N(e,t,r,a){e.innerHTML=`
        <p><label for="nf_page-size">${pageSizeTitle}:</label> <input id="nf_page-size" type="number" min="1" max="100" step="1" value="${t}"
                onkeypress='return event.charCode >= 48 && event.charCode <= 57'/></p>
        <p>${eventTypesTitle}: </p>
        <div id="nf_event-types"></div>
        <p><button id="nf_apply-filter" disabled="true">${applyFilterTitle}</button></p>        
    `;const n=e.querySelector("#nf_page-size"),s=e.querySelector("#nf_apply-filter"),l=e.querySelector("#nf_event-types"),o=c=>{const d=n.valueAsNumber;if(c.target===n&&d===u.pageSize){s.disabled=!0;return}if(d>0&&d<=100){const f=l.querySelectorAll("input");for(let i=0;i<f.length;i++)if(f[i].checked){if(s.disabled=!1,a!==void 0){u.updateFilter();const p=a(u.filter);s.innerText=applyFilterTitle+" ("+p+")"}return}}s.disabled=!0},u={pageSize:t,filter:void 0,pageSizeEl:n,eventTypesEl:l,applyFilterEl:s,newsRequest(){return{pageSize:this.pageSize,filter:this.filter}},setPossibleFilters(c){this.eventTypesEl.innerHTML=c.types.map(v(!1)).join("")+c.extraTypes.map(v(!0)).join(""),l.querySelectorAll("input").forEach(d=>d.addEventListener("change",o))},updateFilter(){const c=l.querySelectorAll("input"),d=[],f=[];for(let i=0;i<c.length;i++)c[i].checked&&(c[i].getAttribute("data-ext")==="true"?f.push(c[i].value):d.push(c[i].value));this.filter={types:d,extraTypes:f}},updatePageSize(){this.pageSize=n.valueAsNumber}};return s.addEventListener("click",function(){this.disabled=!0,u.updateFilter(),u.updatePageSize(),r(u.newsRequest())}),n.addEventListener("change",o),u}function v(e){return t=>`<p><input data-ext="${e}" type="checkbox" checked value="${t}">${typeNames.get(t)??t}</input></p>`}function w(e,t){if(e.length!==t.length)return!1;for(let r=0;r<e.length;r++)if(e[r]!==t[r])return!1;return!0}var g,h=news,m;const T=Math.floor;(()=>{for(var e=0;e<news.length;e++)news[e].id=e;m=q(news)})();function F(e,t){e.innerHTML=z(t)}function P(e){return`news${e}`}function z(e){const t=I();return e.map(r=>`
        <article>
            <div class="anchor" id="${P(r.id)}"></div>
            <header>
                <p>${t(r.time)}</p>
                <h1>${r.title}</h1>
            </header>
            <div>
            ${r.content}
            </div>
            <div style='clear:both'></div>
        </article>`).join("")}function I(){const e={year:"numeric",month:"numeric",day:"numeric"},t=Object.assign({hour:"2-digit",minute:"2-digit"},e);return r=>{let a=new Date(r);return r.length===10||r.indexOf("00:00")!==-1?a.toLocaleDateString(locale,e):a.toLocaleString(locale,t)}}function x(e){return O(e.filter)?(R(e.filter),!0):!1}function $(e,t){return L(e,t,x(t))}function A(e){return E(e).length}function L(e,t,r){const a=e*t.pageSize;return{page:e,total:h.length,filtered:r,news:h.slice(a,a+t.pageSize),calendar:m}}function _(e,t){const r=x(t);for(let a=0;a<h.length;a++)if(h[a].id===e){const n=T(a/t.pageSize);return L(n,t,r)}return null}function O(e){return g===void 0?e!==void 0:e===void 0?!0:!w(g.types,e.types)||!w(g.extraTypes,e.extraTypes)}function R(e){g=e,h=E(e),m=q(h)}function E(e){return e===void 0?news:news.filter(t=>{if(t.extra!==void 0){if(!e.extraTypes.includes(t.extra.type))return!1}else if(!e.types.includes(t.type))return!1;return!0})}function D(){const e=[],t=[];return news.forEach(r=>{r.extra!==void 0?t.includes(r.extra.type)||t.push(r.extra.type):e.includes(r.type)||e.push(r.type)}),{types:e,extraTypes:t}}function q(e){const t=[];for(let r of e){const a=parseInt(r.time.substring(0,4)),n=parseInt(r.time.substring(5,7)),s=b(t,a,r.id);s.children===void 0&&(s.children=[]),b(s.children,n,r.id)}return t}function b(e,t,r){if(e.length===0||e[e.length-1].key!==t){const n={key:t,firstId:r,count:1};return e.push(n),n}const a=e[e.length-1];return a.count++,a}function S(e){const t=y("«"),r=y("»"),a={lastPage:-1,lastTotal:0,page(){return this.lastPage},update(n,s){this.lastTotal!=s?this.reinit(n,s):this.changePage(n)},changePage(n){if(n!=this.lastPage){const s=e.querySelectorAll("a");s[n+1].classList.toggle("active"),s[this.lastPage+1].classList.toggle("active"),this.lastPage=n}},reinit(n,s){e.textContent="",e.appendChild(t);for(let l=0;l<s;l++){const o=y((l+1).toString());l==n&&o.classList.add("active"),e.appendChild(o),o.addEventListener("click",()=>(this.callback(l),!1))}e.appendChild(r),this.lastPage=n,this.lastTotal=s},prev(){this.lastPage>0&&this.callback(this.lastPage-1)},next(){this.lastPage<this.lastTotal-1&&this.callback(this.lastPage+1)},callback:n=>{}};return t.addEventListener("click",()=>(a.prev(),!1)),r.addEventListener("click",()=>(a.next(),!1)),a}function y(e){const t=document.createElement("a");return t.href="#",t.appendChild(document.createTextNode(e)),t}document.querySelector("#app").innerHTML=`
    <header class="pager" id="top-pager"></header>
    <section class="blog-news">
        <aside class="left-panel">
            <details>
                <summary class="details"><span class="level0">${filterTitle}</span></summary>
                <div class="filter" id="news-filter"></div>            
            </details>
            <h3>${newsTotalTitle}: <span id="total-count"></span></h3>
            <div id="news-calendar"></div>
        </aside>
        <main id="news"></main>
    </section>
    <header class="pager" id="bottom-pager"></header>
`;(()=>{const e=document.querySelector("#news"),t=S(document.querySelector("#top-pager")),r=S(document.querySelector("#bottom-pager")),a=document.querySelector("#total-count"),n=document.querySelector("#news-filter"),s=k(document.querySelector("#news-calendar"));s.callback=f;const l=5,o=i=>{if(i.filtered||t.page()!=i.page){a.innerText=i.total.toString();let p=T(i.total/c.pageSize);i.total%c.pageSize>0&&p++,t.update(i.page,p),r.update(i.page,p),F(e,i.news),s.update(i.calendar)}},u=(i,p)=>{o($(i,p))},c=N(n,l,i=>{u(0,i)},i=>A(i));t.callback=i=>{u(i,c.newsRequest())},r.callback=t.callback;const d=H();d!==null?f(d):u(0,c.newsRequest()),c.setPossibleFilters(D());function f(i){const p=_(i,c.newsRequest());p!==null?(o(p),setTimeout(()=>{document.getElementById(P(i)).scrollIntoView({behavior:"instant"})},10)):u(0,c.newsRequest())}})();function H(){const e=window.location.search,r=new URLSearchParams(e).get("news-id");return r!==null?parseInt(r):null}
