(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))i(n);new MutationObserver(n=>{for(const s of n)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(n){const s={};return n.integrity&&(s.integrity=n.integrity),n.referrerPolicy&&(s.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?s.credentials="include":n.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(n){if(n.ep)return;n.ep=!0;const s=r(n);fetch(n.href,s)}})();function z(e){const t={update(n){this.lastData!==n&&(r(n),this.lastData=n)},callback:n=>{}};return t;function r(n){e.innerText="",n.map(s=>{const a=document.createElement("details");a.classList.add("details");const l=document.createElement("summary");l.appendChild(i(s,"level0")),a.appendChild(l);for(let o of s.children)a.appendChild(i(o,"level1",I));return a}).forEach(s=>{e.appendChild(s)})}function i(n,s,a){const l=document.createElement("a");return l.href="#",l.classList.add(s),l.appendChild(document.createTextNode(((a==null?void 0:a(n.key))??n.key)+" ("+n.count+")")),l.addEventListener("click",()=>(t.callback(n.firstId),!1)),l}}function I(e){return months[e-1]}function $(e,t,r){e.innerHTML=`
        <p><label for="nf_page-size">${pageSizeTitle}:</label> <input id="nf_page-size" type="number" min="1" max="100" step="1" value="${t}"
                onkeypress='return event.charCode >= 48 && event.charCode <= 57'/></p>
        <p>${eventTypesTitle}: </p>
        <div id="nf_event-types"></div>
        <p><button id="nf_apply-filter" disabled="true">${applyFilterTitle}</button></p>        
    `;const i=e.querySelector("#nf_page-size"),n=e.querySelector("#nf_apply-filter"),s=e.querySelector("#nf_event-types"),a=o=>{const u=i.valueAsNumber;if(o.target===i){n.disabled=u===l.pageSize;return}if(u>0&&u<=100){const c=s.querySelectorAll("input");for(let p=0;p<c.length;p++)if(c[p].checked){n.disabled=!1,l.updateTotal();return}}n.disabled=!0},l={pageSize:t,filter:void 0,newsRequest(){return{pageSize:this.pageSize,filter:this.filter}},setPossibleTypes(o){s.innerHTML=S(o.types,T(!1))+S(o.extraTypes,T(!0)),s.querySelectorAll("input").forEach(u=>u.addEventListener("change",a)),this.typeCounter=new Map([...o.types,...o.extraTypes]),this.updateTotal()},updateFilter(){const o=s.querySelectorAll("input"),u=[],c=[];for(const p of o)p.checked&&(p.getAttribute("data-ext")==="true"?c.push(p.value):u.push(p.value));u.length===0&&c.length===0?this.filter=void 0:this.filter={types:u,extraTypes:c}},updateTotal(){var c;let o=0;const u=s.querySelectorAll("input");for(const p of u)p.checked&&(o+=((c=this.typeCounter)==null?void 0:c.get(p.value))??0);o===0&&(o=this.newsCount()),n.innerText=applyFilterTitle+" ("+o+")"},updatePageSize(){this.pageSize=i.valueAsNumber},newsCount(){var u;let o=0;return(u=this.typeCounter)==null||u.forEach(c=>{o+=c}),o}};return n.addEventListener("click",function(){this.disabled=!0,l.updateFilter(),l.updatePageSize(),r(l.newsRequest())}),i.addEventListener("change",a),l}function T(e){return(t,r)=>`<p><input data-ext="${e}" type="checkbox" value="${t}">${typeNames.get(t)??t} (${r})</input></p>`}function S(e,t){const r=typeNames.keys(),i=[];for(const n of r)e.has(n)&&i.push(t(n,e.get(n)));return i.join("")}function b(e,t){if(e.length!==t.length)return!1;for(let r=0;r<e.length;r++)if(e[r]!==t[r])return!1;return!0}var g,h=news,m;const L=Math.floor;(()=>{for(var e=0;e<news.length;e++)news[e].id=news.length-e;m=N(news)})();function F(e,t){e.innerHTML=A(t)}function C(e){return`news${e}`}function A(e){const t=M();return e.map(r=>`
        <article>
            <div class="anchor" id="${C(r.id)}"></div>
            <header>
                <p>${t(r.time)}</p>
                <h1>${r.title}</h1>
            </header>
            <div>
            ${r.content}
            </div>
            <div style='clear:both'></div>
        </article>`).join("")}function M(){const e={year:"numeric",month:"numeric",day:"numeric"},t=Object.assign({hour:"2-digit",minute:"2-digit"},e);return r=>{let i=new Date(r);return r.length===10||r.indexOf("00:00")!==-1?i.toLocaleDateString(locale,e):i.toLocaleString(locale,t)}}function k(e){return R(e.filter)?(D(e.filter),!0):!1}function _(e,t){return q(e,t,k(t))}function q(e,t,r){const i=e*t.pageSize;return{page:e,total:h.length,filtered:r,news:h.slice(i,i+t.pageSize),calendar:m}}function O(e,t){const r=k(t);for(let i=0;i<h.length;i++)if(h[i].id===e){const n=L(i/t.pageSize);return q(n,t,r)}return null}function R(e){return g===void 0?e!==void 0:e===void 0?!0:!b(g.types,e.types)||!b(g.extraTypes,e.extraTypes)}function D(e){g=e,h=H(e),m=N(h)}function H(e){return e===void 0?news:news.filter(t=>{if(t.extra!==void 0){if(!e.extraTypes.includes(t.extra.type))return!1}else if(!e.types.includes(t.type))return!1;return!0})}function V(){const e={types:new Map,extraTypes:new Map};return news.forEach(t=>{t.extra!==void 0?P(e.extraTypes,t.extra.type):P(e.types,t.type)}),e}function P(e,t){let r=e.get(t);r===void 0&&(r=0),e.set(t,r+1)}function N(e){const t=[];for(let r of e){const i=parseInt(r.time.substring(0,4)),n=parseInt(r.time.substring(5,7)),s=x(t,i,r.id);s.children===void 0&&(s.children=[]),x(s.children,n,r.id)}return t}function x(e,t,r){if(e.length===0||e[e.length-1].key!==t){const n={key:t,firstId:r,count:1};return e.push(n),n}const i=e[e.length-1];return i.count++,i}function E(e){const t=y("«"),r=y("»"),i={lastPage:-1,lastTotal:0,page(){return this.lastPage},update(n,s){this.lastTotal!=s?this.reinit(n,s):this.changePage(n)},changePage(n){if(n!=this.lastPage){const s=e.querySelectorAll("a");s[n+1].classList.toggle("active"),s[this.lastPage+1].classList.toggle("active"),this.lastPage=n}},reinit(n,s){e.textContent="",e.appendChild(t);for(let a=0;a<s;a++){const l=y((a+1).toString());a==n&&l.classList.add("active"),e.appendChild(l),l.addEventListener("click",()=>(this.callback(a),!1))}e.appendChild(r),this.lastPage=n,this.lastTotal=s},prev(){this.lastPage>0&&this.callback(this.lastPage-1)},next(){this.lastPage<this.lastTotal-1&&this.callback(this.lastPage+1)},callback:n=>{}};return t.addEventListener("click",()=>(i.prev(),!1)),r.addEventListener("click",()=>(i.next(),!1)),i}function y(e){const t=document.createElement("a");return t.href="#",t.appendChild(document.createTextNode(e)),t}document.querySelector("#app").innerHTML=`
    <header class="pager" id="top-pager"></header>
    <section class="blog-news">
        <aside class="left-panel">
            <details>
                <summary><span class="level0">${filterTitle}</span></summary>
                <div class="filter" id="news-filter"></div>            
            </details>
            <h3>${newsTotalTitle}: <span id="total-count"></span></h3>
            <div id="news-calendar"></div>
        </aside>
        <main id="news"></main>
    </section>
    <header class="pager" id="bottom-pager"></header>
`;(()=>{const e=document.querySelector("#news"),t=E(document.querySelector("#top-pager")),r=E(document.querySelector("#bottom-pager")),i=document.querySelector("#total-count"),n=document.querySelector("#news-filter"),s=z(document.querySelector("#news-calendar"));s.callback=v;const a=5;let l=a;const o=d=>{if(d.filtered||t.page()!==d.page||c.pageSize!==l){l=c.pageSize,i.innerText=d.total.toString();let f=L(d.total/c.pageSize);d.total%c.pageSize>0&&f++,t.update(d.page,f),r.update(d.page,f),F(e,d.news),s.update(d.calendar),setupImageViewer(openImageTitle)}},u=(d,f)=>{o(_(d,f))},c=$(n,a,d=>{u(0,d)});t.callback=d=>{u(d,c.newsRequest())},r.callback=t.callback;const p=j();p!==null?v(p):u(0,c.newsRequest()),c.setPossibleTypes(V());function v(d){const f=O(d,c.newsRequest());if(f!==null){let w=function(){document.getElementById(C(d)).scrollIntoView({behavior:"instant"})};o(f),document.readyState==="complete"?w():document.onreadystatechange=function(){document.readyState==="complete"&&w()}}else u(0,c.newsRequest())}})();function j(){const e=window.location.search,r=new URLSearchParams(e).get("news-id");return r!==null?parseInt(r):null}
