(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))i(n);new MutationObserver(n=>{for(const r of n)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(n){const r={};return n.integrity&&(r.integrity=n.integrity),n.referrerPolicy&&(r.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?r.credentials="include":n.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(n){if(n.ep)return;n.ep=!0;const r=s(n);fetch(n.href,r)}})();function I(e){const t={update(n){this.lastData!==n&&(s(n),this.lastData=n)},callback:n=>{}};return t;function s(n){e.innerText="",n.map(r=>{const a=document.createElement("details");a.classList.add("details");const o=document.createElement("summary");o.appendChild(i(r,"level0")),a.appendChild(o);for(let l of r.children)a.appendChild(i(l,"level1",$));return a}).forEach(r=>{e.appendChild(r)})}function i(n,r,a){const o=document.createElement("a");return o.href="#",o.classList.add(r),o.appendChild(document.createTextNode(((a==null?void 0:a(n.key))??n.key)+" ("+n.count+")")),o.addEventListener("click",l=>{t.callback(n.firstId),l.preventDefault()}),o}}function $(e){return months[e-1]}function F(e,t,s){e.innerHTML=`
        <p><label for="nf_page-size">${pageSizeTitle}:</label> <input id="nf_page-size" type="number" min="1" max="100" step="1" value="${t}"
                onkeypress='return event.charCode >= 48 && event.charCode <= 57'/></p>
        <p>${eventTypesTitle}: </p>
        <div id="nf_event-types"></div>
        <p><button id="nf_apply-filter" disabled="true">${applyFilterTitle}</button></p>        
    `;const i=e.querySelector("#nf_page-size"),n=e.querySelector("#nf_apply-filter"),r=e.querySelector("#nf_event-types"),a=l=>{const u=i.valueAsNumber;if(l.target===i){n.disabled=u===o.pageSize;return}if(u>0&&u<=100){const c=r.querySelectorAll("input");for(let p=0;p<c.length;p++)if(c[p].checked){n.disabled=!1,o.updateTotal();return}}n.disabled=!0},o={pageSize:t,filter:void 0,newsRequest(){return{pageSize:this.pageSize,filter:this.filter}},setPossibleTypes(l){r.innerHTML=b(l.types,S(!1))+b(l.extraTypes,S(!0)),r.querySelectorAll("input").forEach(u=>u.addEventListener("change",a)),this.typeCounter=new Map([...l.types,...l.extraTypes]),this.updateTotal()},updateFilter(){const l=r.querySelectorAll("input"),u=[],c=[];for(const p of l)p.checked&&(p.getAttribute("data-ext")==="true"?c.push(p.value):u.push(p.value));u.length===0&&c.length===0?this.filter=void 0:this.filter={types:u,extraTypes:c}},updateTotal(){var c;let l=0;const u=r.querySelectorAll("input");for(const p of u)p.checked&&(l+=((c=this.typeCounter)==null?void 0:c.get(p.value))??0);l===0&&(l=this.newsCount()),n.innerText=applyFilterTitle+" ("+l+")"},updatePageSize(){this.pageSize=i.valueAsNumber},newsCount(){var u;let l=0;return(u=this.typeCounter)==null||u.forEach(c=>{l+=c}),l}};return n.addEventListener("click",function(){this.disabled=!0,o.updateFilter(),o.updatePageSize(),s(o.newsRequest())}),i.addEventListener("change",a),o}function S(e){return(t,s)=>`<p><input data-ext="${e}" type="checkbox" value="${t}">${typeNames.get(t)??t} (${s})</input></p>`}function b(e,t){const s=typeNames.keys(),i=[];for(const n of s)e.has(n)&&i.push(t(n,e.get(n)));return i.join("")}function P(e,t){if(e.length!==t.length)return!1;for(let s=0;s<e.length;s++)if(e[s]!==t[s])return!1;return!0}var g,h=news,m;const C=Math.floor;(()=>{for(var e=0;e<news.length;e++)news[e].id=news.length-e;m=z(news)})();function A(e,t){e.innerHTML=M(t)}function k(e){return`news${e}`}function M(e){const t=_();return e.map(s=>`
        <article>
            <div class="anchor" id="${k(s.id)}"></div>
            <header>
                <p>${t(s.time)}</p>
                <h1>${s.title}</h1>
            </header>
            <div>
            ${s.content}
            </div>
            <div style='clear:both'></div>
        </article>`).join("")}function _(){const e={year:"numeric",month:"numeric",day:"numeric"},t=Object.assign({hour:"2-digit",minute:"2-digit"},e);return s=>{let i=new Date(s);return s.length===10||s.indexOf("00:00")!==-1?i.toLocaleDateString(locale,e):i.toLocaleString(locale,t)}}function q(e){return O(e.filter)?(R(e.filter),!0):!1}function D(e,t){return N(e,t,q(t))}function N(e,t,s){const i=e*t.pageSize;return{page:e,total:h.length,filtered:s,news:h.slice(i,i+t.pageSize),calendar:m}}function H(e,t){const s=q(t);for(let i=0;i<h.length;i++)if(h[i].id===e){const n=C(i/t.pageSize);return N(n,t,s)}return null}function O(e){return g===void 0?e!==void 0:e===void 0?!0:!P(g.types,e.types)||!P(g.extraTypes,e.extraTypes)}function R(e){g=e,h=V(e),m=z(h)}function V(e){return e===void 0?news:news.filter(t=>{if(t.extra!==void 0){if(!e.extraTypes.includes(t.extra.type))return!1}else if(!e.types.includes(t.type))return!1;return!0})}function j(){const e={types:new Map,extraTypes:new Map};return news.forEach(t=>{t.extra!==void 0?x(e.extraTypes,t.extra.type):x(e.types,t.type)}),e}function x(e,t){let s=e.get(t);s===void 0&&(s=0),e.set(t,s+1)}function z(e){const t=[];for(let s of e){const i=parseInt(s.time.substring(0,4)),n=parseInt(s.time.substring(5,7)),r=E(t,i,s.id);r.children===void 0&&(r.children=[]),E(r.children,n,s.id)}return t}function E(e,t,s){if(e.length===0||e[e.length-1].key!==t){const n={key:t,firstId:s,count:1};return e.push(n),n}const i=e[e.length-1];return i.count++,i}function L(e){const t=y("«"),s=y("»"),i={lastPage:-1,lastTotal:0,page(){return this.lastPage},update(n,r){this.lastTotal!=r?this.reinit(n,r):this.changePage(n)},changePage(n){if(n!=this.lastPage){const r=e.querySelectorAll("a");r[n+1].classList.toggle("active"),r[this.lastPage+1].classList.toggle("active"),this.lastPage=n}},reinit(n,r){e.textContent="",e.appendChild(t);for(let a=0;a<r;a++){const o=y((a+1).toString());a==n&&o.classList.add("active"),e.appendChild(o),o.addEventListener("click",()=>{this.callback(a)})}e.appendChild(s),this.lastPage=n,this.lastTotal=r},prev(){this.lastPage>0&&this.callback(this.lastPage-1)},next(){this.lastPage<this.lastTotal-1&&this.callback(this.lastPage+1)},callback:n=>{}};return t.addEventListener("click",()=>(i.prev(),!1)),s.addEventListener("click",()=>(i.next(),!1)),i}function y(e){const t=document.createElement("a");return t.href="#",t.appendChild(document.createTextNode(e)),t}document.querySelector("#app").innerHTML=`
    <header class="pager" id="top-pager"></header>
    <section class="blog-news">
        <aside class="left-panel">
            <details>
                <summary><span class="level0">${filterTitle}</span></summary>
                <div class="filter" id="news-filter"></div>            
            </details>
            <h3>${newsTotalTitle}: <span id="total-count"></span></h3>
            <div id="news-calendar"></div>
        </aside>
        <main id="news"></main>
    </section>
    <header class="pager" id="bottom-pager"></header>
`;(()=>{const e=document.querySelector("#news"),t=L(document.querySelector("#top-pager")),s=L(document.querySelector("#bottom-pager")),i=document.querySelector("#total-count"),n=document.querySelector("#news-filter"),r=I(document.querySelector("#news-calendar"));r.callback=v;const a=5;let o=a;const l=d=>{if(d.filtered||t.page()!==d.page||c.pageSize!==o){o=c.pageSize,i.innerText=d.total.toString();let f=C(d.total/c.pageSize);d.total%c.pageSize>0&&f++,t.update(d.page,f),s.update(d.page,f),A(e,d.news),r.update(d.calendar),setupImageViewer(openImageTitle)}},u=(d,f)=>{l(D(d,f))},c=F(n,a,d=>{u(0,d)});t.callback=d=>{u(d,c.newsRequest())},s.callback=t.callback;const p=B();p!==null?v(p):u(0,c.newsRequest()),c.setPossibleTypes(j());function v(d){const f=H(d,c.newsRequest());if(f!==null){let w=function(){const T=document.getElementById(k(d));T.offsetHeight,setTimeout(()=>{T.scrollIntoView({behavior:"instant"})},100)};l(f),document.readyState==="complete"?w():document.onreadystatechange=function(){document.readyState==="complete"&&w()}}else u(0,c.newsRequest())}})();function B(){const e=window.location.search,s=new URLSearchParams(e).get("news-id");return s!==null?parseInt(s):null}
